### ISSUE TITLE
wedish_store kategorijos

### ISSUE THREAD

**Issue by infohata** [WeDish/wedish_backend#5]
Atlikti trumpą tyrimą ir išrinkti kategorijų medžiui tinkamą sprendimą (mptt ar treebeard)
Modelis Produkto Kategorijai `Category`, panaudoti Treebeard arba MPTT medžio struktūrai. Jeigu projekte nėra - suinstaliuoti.

**Comment by infohata** [comment]
requires #4

**Comment by tomuko17** [comment]
Kategorijų medžiui nuspręsta naudoti treebeard
