### ISSUE TITLE
wedish_recipy

### ISSUE THREAD

**Issue by infohata** [WeDish/wedish_backend#6]
Appsas

# modeliai
`Dish`
`Drink`

objektuose produktų FK eina į #4 esančius produktus

**Comment by vtutkus** [comment]
dish ir drink traukiu kaip atskiras kategorijas vienoje DB lenteleje

**Comment by vtutkus** [comment]
numatomi laukai:
name = models.CharField
category = models.PositiveIntegerField
recommended_retail_price = models.DecimalField
picture = models.ImageField
description = HTMLField
created_at = models.DateTimeField

**Comment by infohata** [comment]
GoodIngradient
* good fk to Good
* ingradient fk to store.Product
* quantity
* unit fk to store.Unit (on_save if Null set to Product.unit)

**Comment by vtutkus** [comment]
@infohata pull requestas issiustas
